server {
    listen 8080;

    # Use relative redirects to avoid port mismatches
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location /_nuxt/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
